# Generated by cucumber-sinatra. (2012-11-10 03:03:05 +0400)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/sincucr18n.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = SinCucR18n

class SinCucR18nWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SinCucR18nWorld.new
end
